rootProject.name = 'monosodium-glutamate'

include 'msg-clikt'
include 'msg-encodings'
include 'msg-grpc'
include 'msg-kafka'
include 'msg-kafka-clikt'
include 'msg-predicates'
include 'msg-protobuf'
include 'msg-protobuf-clikt'
include 'msg-progressbar'
include 'msg-schemas'

include 'kat'
include 'kgb'
include 'pqt'
include 'proto2'
include 'qs'

