plugins {
  id 'org.jetbrains.kotlin.jvm'
  id 'distribution'
}
repositories {
  mavenCentral()
}

dependencies {
  implementation group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib'
  testImplementation group: 'junit', name: 'junit', version: '4.11'
  testImplementation group: 'org.jetbrains.kotlin', name: 'kotlin-test-junit'
  implementation project(':msg-clikt')
  implementation project(':msg-encodings')
  implementation project(':msg-progressbar')
  implementation project(':msg-protobuf-clikt')
  implementation project(':msg-schemas')

  implementation group: 'com.squareup.wire', name: 'wire-compiler', version: '6.2.0'
  implementation group: 'com.google.protobuf', name: 'protobuf-java-util', version: protobufVersion
  implementation group: 'io.grpc', name: 'grpc-netty', version: grpcVersion
}

build {
  dependsOn("installDist")
}

jar {
  manifest {
    attributes(
        'Class-Path': configurations.runtimeClasspath.collect { 'dependencies/' + it.getName() }.join(' '),
        'Implementation-Title': project.name,
        'Implementation-Version': project.version,
        'Main-Class': 'msg.proto.MainKt',
        )
  }
}

distributions {
  main {
    distributionBaseName = project.name
    contents {
      into("") {
        from jar.archiveFile
      }
      into("dependencies") {
        from configurations.runtimeClasspath
      }
    }
  }
}
